### ISSUE TITLE
What is nbproject???

### ISSUE THREAD

**Issue by shesl-meow** [DaHoC/ftpserver#1]
I get these issues while execute `make`:
```bash
$ make
makefile:106: nbproject/Makefile-impl.mk: No such file or directory
makefile:109: nbproject/Makefile-variables.mk: No such file or directory
make: *** 没有规则可以创建目标“nbproject/Makefile-variables.mk”。 停止。
```

**Comment by DaHoC** [comment]
`nbproject` means it was created using Netbeans (a few years back, did not expect anyone to use this code)
I will have a look when I have some time

**Comment by DaHoC** [comment]
Fixed the makefile, run `make all` to compile now works again. See Readme for updated instructions, also I just added a rather open/user-friendly license
