### ISSUE TITLE
More details on how to use?

### ISSUE THREAD

**Issue by ghost** [DaHoC/ftpserver#2]
I really like the simplicity of your repository, but as someone who is not as familiar with the command line as I wish I would, could you please tell me more in the `README` about this (besides the command arguments)?

One thing I would like to know, additionally, is how (or if) it can send files to other computers. Would you be able to supply this information?

**Comment by DaHoC** [comment]
If you want to send files to the ftp server, use the `upload file` command as written in the README. If you then want to download again, use the `download file` command.
That way, if the `ftpserver` is running on another computer that is accessible via FTP standard ports, you can transfer files.

Please note that this is a playground project written for fun, and the ftp commands don't fully conform to the FTP standard, making it probably incompatible with other FTP clients than the provided CLI.
Furthermore, I did not run or test this code in a long time.
